name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit_test:
    name: Unit tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Set up JDK
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Test with Gradle
        run: ./gradlew --no-daemon --continue test
      - name: Upload test coverage
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e

  smoke_tests:
    name: Smoke tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5
        with:
          install: true

      - name: Build Docker image and store in cache
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          context: .
          push: false
          load: true
          tags: exercism/java-analyzer
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests in Docker
        run: bin/run-tests-in-docker.sh
